<template>
  <div class="home-page">
    <header class="header">
      <h1>搭一把</h1>
      <p>描述你的搭子需求，一键生成分享页面</p>
    </header>

    <main class="main">
      <form @submit="onSubmit">
        <!-- Raw Text Input with VeeValidate -->
        <Field name="rawText" v-slot="{ field, errors }">
          <div class="field-wrapper">
            <PRInput
              :model-value="field.value"
              @update:model-value="field.onChange"
              :disabled="mutation.isPending.value"
            />
            <span v-if="errors.length" class="error-message">
              {{ errors[0] }}
            </span>
          </div>
        </Field>

        <!-- PIN Input with VeeValidate -->
        <Field name="pin" v-slot="{ field, errors }">
          <div class="field-wrapper">
            <PINInput :model-value="field.value" @update:model-value="field.onChange" />
            <span v-if="errors.length" class="error-message">
              {{ errors[0] }}
            </span>
          </div>
        </Field>

        <!-- Always Enabled Submit Button -->
        <SubmitButton
          type="submit"
          :loading="mutation.isPending.value"
        >
          解析我的需求
        </SubmitButton>
      </form>

      <LoadingState
        v-if="mutation.isPending.value"
        message="正在解析你的需求..."
      />

      <ErrorToast
        v-if="mutation.isError.value"
        :message="mutation.error.value?.message || '创建失败'"
        @close="mutation.reset()"
      />
    </main>

    <!-- Visualization Modal -->
    <ParseVisualizationModal
      :open="showModal"
      :raw-text="formValues.rawText || ''"
      @close="showModal = false"
      @complete="handleVisualizationComplete"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useForm, Field } from "vee-validate";
import { createPRValidationSchema } from "@/lib/validation";
import PRInput from "@/components/PRInput.vue";
import PINInput from "@/components/PINInput.vue";
import SubmitButton from "@/components/SubmitButton.vue";
import LoadingState from "@/components/LoadingState.vue";
import ErrorToast from "@/components/ErrorToast.vue";
import ParseVisualizationModal from "@/components/ParseVisualizationModal.vue";
import { useCreatePR } from "@/queries/useCreatePR";
import { useUserPRStore } from "@/stores/userPRStore";
import type { PRId } from "@partner-up-dev/backend";

const router = useRouter();
const mutation = useCreatePR();
const userPRStore = useUserPRStore();

const showModal = ref(false);
const pendingResult = ref<{ id: PRId } | null>(null);

// VeeValidate form setup with Zod schema
const { handleSubmit, values: formValues } = useForm({
  validationSchema: createPRValidationSchema,
  initialValues: {
    rawText: '',
    pin: '', // Will be auto-generated by PINInput component
  },
});

// Submit handler (validation runs automatically)
const onSubmit = handleSubmit(async (values) => {
  // Show visualization modal
  showModal.value = true;

  try {
    // Submit to backend
    const result = await mutation.mutateAsync({
      rawText: values.rawText,
      pin: values.pin,
    });
    pendingResult.value = result;
  } catch (error) {
    showModal.value = false;
    // Error will be shown via ErrorToast
    console.error("Submission error:", error);
  }
});

const handleVisualizationComplete = () => {
  showModal.value = false;
  if (pendingResult.value) {
    // Store creator ID using Pinia store
    userPRStore.addCreatedPR(pendingResult.value.id);
    router.push(`/pr/${pendingResult.value.id}`);
  }
};
</script>

<style lang="scss" scoped>
.home-page {
  max-width: 480px;
  margin: 0 auto;
  padding: var(--sys-spacing-med);
  min-height: 100vh;
}

.header {
  text-align: center;
  padding: var(--sys-spacing-lg) 0;

  h1 {
    @include mx.pu-font(headline-large);
    color: var(--sys-color-primary);
    margin-bottom: var(--sys-spacing-sm);
  }

  p {
    @include mx.pu-font(body-large);
    color: var(--sys-color-on-surface-variant);
  }
}

.main {
  display: flex;
  flex-direction: column;
  gap: var(--sys-spacing-med);
}

form {
  display: flex;
  flex-direction: column;
  gap: var(--sys-spacing-med);
}

.field-wrapper {
  display: flex;
  flex-direction: column;
  gap: var(--sys-spacing-xs);
}

.error-message {
  color: var(--sys-color-error);
  font-size: 0.875rem;
  display: flex;
  align-items: center;
  gap: var(--sys-spacing-xs);

  &::before {
    content: '⚠';
  }
}
</style>
