export const acceptedTelemetryEventTypes = [
  "page_view",
  "pr_create_result",
  "pr_join_result",
  "pr_waitlist_result",
  "pr_exit_success",
  "pr_confirm_success",
  "pr_checkin_submitted",
  "share_method_switch",
  "share_link_native_success",
  "share_link_copy_success",
  "share_link_failed",
  "share_session_started",
  "share_descriptor_submitted",
  "share_descriptor_discarded_stale",
  "share_apply_fallback_success",
  "share_apply_base_success",
  "share_apply_enriched_success",
  "share_apply_failed",
  "share_replay_triggered",
  "home_hero_primary_click",
  "home_event_section_impression",
  "home_event_card_impression",
  "home_event_card_click",
  "home_event_all_click",
  "home_event_highlight_click",
  "home_event_plaza_entry_click",
  "home_create_entry_click",
  "home_bookmark_nudge_shown",
  "home_bookmark_action_click",
  "anchor_event_form_impression",
  "anchor_event_form_started",
  "anchor_event_form_recommendation_impression",
  "anchor_event_recommendation_result",
  "anchor_event_form_result_action_click",
  "anchor_event_form_create_fallback_click",
  "event_assisted_create_result",
  "pr_primary_cta_impression",
  "pr_primary_cta_click",
  "pr_lane_expand",
  "pr_recovery_accept",
  "pr_secondary_action_click",
] as const;

export type TelemetryEventType = (typeof acceptedTelemetryEventTypes)[number];
